export const structure_limit = {
    1: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 1,
        STRUCTURE_EXTENSION: 0,
        STRUCTURE_RAMPART: 0,
        STRUCTURE_WALL: 0,
        STRUCTURE_TOWER: 0,
        STRUCTURE_STORAGE: 0,
        STRUCTURE_LINK: 0,
        STRUCTURE_EXTRACTOR: 0,
        STRUCTURE_LAB: 0,
        STRUCTURE_TERMINAL: 0,
        STRUCTURE_FACTORY: 0,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    2: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 1,
        STRUCTURE_EXTENSION: 5,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 0,
        STRUCTURE_STORAGE: 0,
        STRUCTURE_LINK: 0,
        STRUCTURE_EXTRACTOR: 0,
        STRUCTURE_LAB: 0,
        STRUCTURE_TERMINAL: 0,
        STRUCTURE_FACTORY: 0,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    3: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 1,
        STRUCTURE_EXTENSION: 10,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 1,
        STRUCTURE_STORAGE: 0,
        STRUCTURE_LINK: 0,
        STRUCTURE_EXTRACTOR: 0,
        STRUCTURE_LAB: 0,
        STRUCTURE_TERMINAL: 0,
        STRUCTURE_FACTORY: 0,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    4: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 1,
        STRUCTURE_EXTENSION: 20,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 1,
        STRUCTURE_STORAGE: 1,
        STRUCTURE_LINK: 0,
        STRUCTURE_EXTRACTOR: 0,
        STRUCTURE_LAB: 0,
        STRUCTURE_TERMINAL: 0,
        STRUCTURE_FACTORY: 0,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    5: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 1,
        STRUCTURE_EXTENSION: 30,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 2,
        STRUCTURE_STORAGE: 1,
        STRUCTURE_LINK: 2,
        STRUCTURE_EXTRACTOR: 0,
        STRUCTURE_LAB: 0,
        STRUCTURE_TERMINAL: 0,
        STRUCTURE_FACTORY: 0,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    6: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 1,
        STRUCTURE_EXTENSION: 40,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 2,
        STRUCTURE_STORAGE: 1,
        STRUCTURE_LINK: 3,
        STRUCTURE_EXTRACTOR: 1,
        STRUCTURE_LAB: 3,
        STRUCTURE_TERMINAL: 1,
        STRUCTURE_FACTORY: 0,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    7: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 2,
        STRUCTURE_EXTENSION: 50,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 3,
        STRUCTURE_STORAGE: 1,
        STRUCTURE_LINK: 4,
        STRUCTURE_EXTRACTOR: 1,
        STRUCTURE_LAB: 6,
        STRUCTURE_TERMINAL: 1,
        STRUCTURE_FACTORY: 1,
        STRUCTURE_OBSERVER: 0,
        STRUCTURE_POWER_SPAWN: 0,
        STRUCTURE_NUKER: 0,
    },
    8: {
        STRUCTURE_CONTAINER: 5,
        STRUCTURE_SPAWN: 3,
        STRUCTURE_EXTENSION: 60,
        STRUCTURE_RAMPART: Infinity,
        STRUCTURE_WALL: Infinity,
        STRUCTURE_TOWER: 6,
        STRUCTURE_STORAGE: 1,
        STRUCTURE_LINK: 6,
        STRUCTURE_EXTRACTOR: 1,
        STRUCTURE_LAB: 10,
        STRUCTURE_TERMINAL: 1,
        STRUCTURE_FACTORY: 1,
        STRUCTURE_OBSERVER: 1,
        STRUCTURE_POWER_SPAWN: 1,
        STRUCTURE_NUKER: 1,
    }
}

export const creep_format: {
    [level: number]: {
        [role: string]: Array<BodyPartConstant>
    }
} = {
    1: {
        miner: [...Array<BodyPartConstant>(2).fill(WORK), ...Array<BodyPartConstant>(2).fill(MOVE)],
        carrier: [...Array<BodyPartConstant>(3).fill(CARRY), ...Array<BodyPartConstant>(3).fill(MOVE)],
        worker: [...Array<BodyPartConstant>(1).fill(WORK), ...Array<BodyPartConstant>(1).fill(CARRY), ...Array<BodyPartConstant>(2).fill(MOVE)],
    },
    2: {
        miner: [...Array<BodyPartConstant>(3).fill(WORK), ...Array<BodyPartConstant>(3).fill(MOVE)],
        carrier: [...Array<BodyPartConstant>(5).fill(CARRY), ...Array<BodyPartConstant>(5).fill(MOVE)],
        worker: [...Array<BodyPartConstant>(2).fill(WORK), ...Array<BodyPartConstant>(2).fill(CARRY), ...Array<BodyPartConstant>(2).fill(MOVE)],
    },
    3: {
        miner: [...Array<BodyPartConstant>(5).fill(WORK), ...Array<BodyPartConstant>(5).fill(MOVE)],
        carrier: [...Array<BodyPartConstant>(8).fill(CARRY), ...Array<BodyPartConstant>(8).fill(MOVE)],
        worker: [...Array<BodyPartConstant>(4).fill(WORK), ...Array<BodyPartConstant>(4).fill(CARRY), ...Array<BodyPartConstant>(4).fill(MOVE)],
    }
}

export const my_room_information: {[roomName: string]: {
    spawnName: string[]
}} = {
    "sim": {
        spawnName: ["Spawn1"],
    }
}
